database:
  autoMigrate: true # Migrate the database schema on startup
  database: cdr # Database name
  driver: clickhouse # Database driver
  host: localhost # ClickHouse host
  limit: 5000 # Large batch size for ClickHouse performance
  password: your_password_here # ClickHouse password (empty for default user: "")
  port: 9000 # ClickHouse native port (9000 for native, 8123 for HTTP)
  username: default # ClickHouse username
  SSL: false # Use secure connection (true/false)

logging:
  compress: false # Compress log files
  level: info # Logging level (debug|info|warn|error|fatal|panic)
  maxAge: 30 # Maximum age of log files in days
  maxSize: 100 # Maximum size of log files in megabytes
  name: go-cdr-clickhouse.log # Name of the log files
  path: ./logs # Path to store log files

parser:
  parseInterval: 30 # Interval in minutes to parse files
  directories:
  - input: ./cdr-data/data_cucm # Path to the CUCM CDR files
    output: ./cdr-data/data_cucm/processed # Path to move the CDR files after parsing
    type: cucm # Type of CDR files (cucm|cube)
    deleteOriginal: false # Delete original files after parsing
  - input: ./cdr-data/data_cube # Path to the CUBE CDR files
    output: ./cdr-data/data_cube/processed # Path to move the CDR files after parsing
    type: cube # Type of CDR files (cucm|cube)
    deleteOriginal: false # Delete original files after parsing 