database:
  autoMigrate: true # Migrate the database schema on startup
  database: go_cdr # Database name
  driver: postgres # Database driver (mysql|mssql|postgres|sqlite|clickhouse)
  host: localhost # PostgreSQL host
  limit: 100 # Maximum number of records to insert in bulk
  password: your_password_here # PostgreSQL password
  port: 5432 # PostgreSQL port (default 5432)
  username: postgres # PostgreSQL username
  SSL: disable # PostgreSQL SSL mode (disable|require|verify-ca|verify-full)

logging:
  compress: false # Compress log files
  level: info # Logging level (debug|info|warn|error|fatal|panic)
  maxAge: 30 # Maximum age of log files in days
  maxSize: 100 # Maximum size of log files in megabytes
  name: go-cdr-postgres.log # Name of the log files
  path: ./logs # Path to store log files

parser:
  parseInterval: 30 # Interval in minutes to parse files
  directories:
  - input: ./cdr-data/data_cucm # Path to the CUCM CDR files
    output: ./cdr-data/data_cucm/processed # Path to move the CDR files after parsing
    type: cucm # Type of CDR files (cucm|cube)
    deleteOriginal: false # Delete original files after parsing
  - input: ./cdr-data/data_cube # Path to the CUBE CDR files
    output: ./cdr-data/data_cube/processed # Path to move the CDR files after parsing
    type: cube # Type of CDR files (cucm|cube)
    deleteOriginal: false # Delete original files after parsing 